apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-s3-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garage-s3-operator-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
# Cluster-wide permissions for the operator to manage its CRD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: garage-s3-operator-clusterrole
rules:
  - apiGroups: ["garage-s3-operator.abucquet.com"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garage-s3-operator-binding
subjects:
  - kind: ServiceAccount
    name: garage-s3-operator
roleRef:
  kind: Role
  name: garage-s3-operator-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: garage-s3-operator-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: garage-s3-operator
    namespace: garage
roleRef:
  kind: ClusterRole
  name: garage-s3-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
