apiVersion: v1
kind: Secret
metadata:
  name: example-admin-token
  namespace: garage
type: Opaque
stringData:
  # Replace the value below with the real admin token.
  token: "9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d"